#!/usr/bin/python3


def raise_exception_msg(message=""):
    """Raise exception of NameError with message."""
    raise NameError(message)
